### ISSUE TITLE
FileNotFoundError during setup.py install when attempting to run cmake

### ISSUE THREAD

**Issue by Harshil783** [TkinterEP/python-tkextrafont#4]
Well tbh, I can't think of anything in this matter as I was doing some changes in package and testing and all.
**Note: I haven't touched the setup.py and try changes in tkextrafont's init method**

Platform: Windows

![image](https://user-images.githubusercontent.com/52579448/170298377-d27f977c-c985-4d7e-b978-6a85e1db9be2.png)

**Comment by RedFantom** [comment]
Hello! In case you have not found the problem yet, I think I could shed some light on this error message. It's specific to the build system.

`cmake`, the command, was not found on your PATH. I don't know why, but maybe you have to update your PATH variable manually to include to path to the `cmake` executable?

**Comment by Harshil783** [comment]
`cmake` is already in the path!

**Comment by RedFantom** [comment]
So if you were to use the command `cmake .` from MSYS in that very same folder, what is the output?

Because the `FileNotFoundError` is because Windows cannot create a process using the `cmake` executable, because it cannot find it. It looks in the current working directory, and on the `PATH`.

**Comment by RedFantom** [comment]
My suggestion in this case would be to try and vary the line [here](https://github.com/TkinterEP/python-tkextrafont/blob/master/setup.py#L65), so that you specify the full path to your CMake executable.

It could be that the `sp.Popen` call actually doesn't inherit the `PATH` variable from the process calling it, and your `cmake` needs to not just be available in the MSYS Terminal, but globally. I'm not sure, and would find that really weird, but I will test it when I have time. I also have to fix my own MSYS setup again, because I'm getting GPG key errors again...

**Comment by Harshil783** [comment]
### My Progress:
1. Cmake is available at the global path.
2. I tried changing a bit and found that problem might be with the MinGW or Makefile _(I guess)_.
3. I am pretty poor with CMake, so you would have to take care of the CMakeLists.txt.


**Executed in interpreter**:
```
"""sp.run() and sp.call() have same results."""


>>> sp.run([r"C:\Program Files\CMake\bin\cmake.exe", ".", "-G", "MinGW Makefiles"])

CMake Deprecation Warning at CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.
  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: F:/CodeBlocks/MinGW/bin/gcc.exe
-- Check for working C compiler: F:/CodeBlocks/MinGW/bin/gcc.exe - broken
-- Configuring incomplete, errors occurred!
See also "F:/Harshil_Folder/Projects/git_projects/python-tkextrafont/CMakeFiles/CMakeOutput.log".
See also "F:/Harshil_Folder/Projects/git_projects/python-tkextrafont/CMakeFiles/CMakeError.log".
CMake Error at C:/Program Files/CMake/share/cmake-3.22/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler
    "F:/CodeBlocks/MinGW/bin/gcc.exe"
  is not able to compile a simple test program.
  It fails with the following output:
    Change Dir: F:/Harshil_Folder/Projects/git_projects/python-tkextrafont/CMakeFiles/CMakeTmp
    
    Run Build Command(s):F:/CodeBlocks/MinGW/bin/mingw32-make.exe -f Makefile cmTC_88e56/fast && F:/CodeBlocks/MinGW/bin/mingw32-make.exe  -f CMakeFiles\cmTC_88e56.dir\build.make CMakeFiles/cmTC_88e56.dir/build
    mingw32-make.exe[1]: Entering directory 'F:/Harshil_Folder/Projects/git_projects/python-tkextrafont/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_88e56.dir/testCCompiler.c.obj
    F:\CodeBlocks\MinGW\bin\gcc.exe    -o CMakeFiles\cmTC_88e56.dir\testCCompiler.c.obj -c F:\Harshil_Folder\Projects\git_projects\python-tkextrafont\CMakeFiles\CMakeTmp\testCCompiler.c
    mingw32-make.exe[1]: *** [CMakeFiles\cmTC_88e56.dir\build.make:77: CMakeFiles/cmTC_88e56.dir/testCCompiler.c.obj] Error 1
    mingw32-make.exe[1]: Leaving directory 'F:/Harshil_Folder/Projects/git_projects/python-tkextrafont/CMakeFiles/CMakeTmp'
    mingw32-make.exe: *** [Makefile:126: cmTC_88e56/fast] Error 2
```

**Comment by RedFantom** [comment]
Ah, it seems you have multiple versions of CMake and the GNU C compiler installed. That complicates matters. 

It is essential that you use the `MSYS` version of both of those program. That is: `cmake` and `gcc` must be taken from the `C:\MSYS2\mingw64\bin` directory (assuming you installed to `C:\MSYS2`, which is the default). Hence, you must adjust your path so that `C:\Program Files\CMake` and `C:\CodeBlocks\MinGW\bin` are _not_ on it in your MSYS environment.

I suggest overwriting your PATH (only within MSYS!) to:
`/usr/local/bin:/usr/bin:/bin:/opt/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/wbem:/c/Windows/System32/WindowsPowerShell/v1.0`, which is the default I think.

**Comment by RedFantom** [comment]
But you also get the output `warning: mingw-w64-x86_64-make-4.3-1 is up to date -- skipping`, so clearly make is already installed. `mingw32-make` should be available by just typing the command in the MSYS terminal. Does it run then?

**Comment by Harshil783** [comment]
After running `mingw32-make` command following was the output:

```
$ mingw32-make
bash: mingw32-make: command not found

```
